### ISSUE TITLE
ndmg downloads atlases from the web

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/ndmg#3]
There are two problems with this:
- assumption that you will have internet access
- assumption that website serving the atlases will be up
- lack of reproducibility; even though you can run the same container on the same input data if the downloadable atlases changed you will get different results

Solution: make atlases part of the container.

**Comment by gkiar** [comment]
Great idea! As a part of my build script should I download them, then, or
just include them all in this repository?

## 

Greg Kiar gkiar07@gmail.com

**Comment by chrisgorgo** [comment]
You can download them in the Dockerfile - this way they will not be
duplicated. To make this singularity compatible keep the atlases in folder
that will not be mounted: so not in $HOME, /scratch, /tmp etc.

**Comment by gkiar** [comment]
Addressed in https://github.com/neurodata/ndmg/pull/96 and https://github.com/BIDS-Apps/ndmg/commit/80090062345e3e7a8723ed06565e995311d11a26. Thanks!
