### ISSUE TITLE
Add Amazon Container Registry push upon circleci validation

### ISSUE THREAD

**Issue by gkiar** [BIDS-Apps/ndmg#9]
As well as pushing to Docker hub. This makes using Amazon's ECS and Beanstalk a more natural process without having to commit images manually.

https://circleci.com/blog/circleci-aws-ecrecs/

**Comment by chrisgorgo** [comment]
Is there a tutorial describing how to spin up EC2 instances with a given
set of data and run an image from ECS on it?

**Comment by gkiar** [comment]
Working on making that, currently. I should have made enough progress to give a more substantial answer by next week. It does look promising, though -- at least when the data begins in S3 and the container is prepared to pull it.

**Comment by chrisgorgo** [comment]
Awesome. Looking forward.
